### ISSUE TITLE
Rambutan wi-fi issues 

### ISSUE THREAD

**Issue by alex-nozhkin** [8devices/openwrt-8devices#1]
I got the Rambutan-DVK kit, but I have an issue with Wi-Fi interface.

Web interface informed me that “Wireless is disabled or not associated”. 

I change setting for wireless
"
root@Rambutan:/# cat /overlay/upper/etc/config/wireless

config wifi-device 'radio0'
option type 'mac80211'
option channel '11'
option hwmode '11g'
option path 'platform/qca955x_wmac'
option htmode 'HT20'
option disabled '0'

config wifi-iface
option device 'radio0'
option network 'lan'
option mode 'ap'
option encryption 'none'
option ssid 'Rambutan'
"
but wi-fi as before do`t visible.

Firmware Version	OpenWrt-8devices Designated Driver v2.9 unknown / LuCI c46963613f7f1312dac62e507346777ba6f8d8a6 branch (git-16.147.57672-c469636)

I noticed in boot log this message 
"
[   13.223060] ath9k qca955x_wmac: failed to initialize device
[   13.228788] ath9k: probe of qca955x_wmac failed with error -22
"

**Comment by mantas-p** [comment]
Hello,

Please try deleting ```/lib/firmware/soc_wmac.eeprom``` file and rebooting the board.

**Comment by alex-nozhkin** [comment]
I used your recommendation, and we got additional errors.
"
[   13.251545] ath9k qca955x_wmac: Direct firmware load for soc_wmac.eeprom failed with error -2
[   13.260240] ath9k qca955x_wmac: Falling back to user helper
[   13.357265] firmware soc_wmac.eeprom: firmware_loading_store: map pages failed
[   13.365175] ath: phy0: Unable to load EEPROM file soc_wmac.eeprom
[   13.371367] ath9k qca955x_wmac: failed to initialize device
[   13.377096] ath9k: probe of qca955x_wmac failed with error -22
[   21.127343] device eth0 entered promiscuous mode

"

**Comment by mantas-p** [comment]
Please attach output of command ```hexdump -C /dev/mtd2```
Are you using firmware that the device came with?

**Comment by alex-nozhkin** [comment]
root@Rambutan:/# hexdump -C /dev/mtd2
00000000  c4 93 00 07 72 e2 c4 93  00 07 72 e3 ff ff ff ff  |....r.....r.....|
00000010  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00001000  02 02 c4 93 00 07 72 e1  38 44 45 56 31 34 30 30  |......r.8DEV1400|
00001010  00 32 45 31 00 00 00 00  00 00 00 00 00 00 1f 00  |.2E1............|
00001020  33 03 00 00 00 00 04 00  20 00 4d 04 03 00 08 ff  |3....... .M.....|
00001030  00 00 00 00 00 00 00 00  00 11 11 01 00 00 00 00  |................|
00001040  00 00 00 00 00 00 00 00  00 23 00 00 00 00 00 00  |.........#......|
00001050  ff 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00001060  0e 0e 03 00 2c e2 00 02  0e 1c 00 00 00 00 00 00  |....,...........|
00001070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00001080  48 00 37 37 00 4b 4b 00  00 00 70 8e ac 05 00 92  |H.77.KK...p.....|
00001090  00 00 00 08 00 93 00 00  00 0a 00 91 00 00 00 00  |................|
000010a0  00 92 00 00 00 02 00 91  00 00 00 04 00 91 00 00  |................|
000010b0  00 7f 00 82 00 00 00 7f  00 82 00 00 00 7f 00 82  |................|
000010c0  00 00 00 70 ac 70 8e ac  70 8e ac 70 8e ac 29 29  |...p.p..p..p..))|
000010d0  29 29 29 29 29 29 29 29  29 29 29 29 29 29 29 29  |))))))))))))))))|
000010e0  29 29 29 28 27 26 25 24  27 26 25 24 27 26 25 24  |)))('&%$'&%$'&%$|
000010f0  29 28 27 26 25 24 27 26  25 24 27 26 25 24 29 28  |)('&%$'&%$'&%$)(|
00001100  27 26 25 24 27 26 25 24  27 26 25 24 29 28 27 26  |'&%$'&%$'&%$)('&|
00001110  25 24 27 26 25 24 27 26  25 24 29 28 27 26 25 24  |%$'&%$'&%$)('&%$|
00001120  27 26 25 24 27 26 25 24  29 28 27 26 25 24 27 26  |'&%$'&%$)('&%$'&|
00001130  25 24 27 26 25 24 11 12  15 17 41 42 45 47 31 32  |%$'&%$....ABEG12|
00001140  35 37 70 75 9d a2 70 75  a2 ff 70 75 a2 ff 7a 7f  |57pu..pu..pu..z.|
00001150  93 98 70 75 ac b8 70 75  ac 00 70 75 ac 00 7a 7f  |..pu..pu..pu..z.|
00001160  93 a2 70 75 ac 00 70 75  ac 00 70 75 ac 00 7a 7f  |..pu..pu..pu..z.|
00001170  93 a2 3c 7c 3c 3c 3c 7c  3c 3c 7c 3c 3c 7c 7c 3c  |..<|<<<|<<|<<||<|
00001180  3c 3c 3c 7c 3c 3c 3c 7c  3c 3c 3c 7c 7c 3c 3c 7c  |<<<|<<<|<<<||<<||
00001190  3c 3c 3c 7c 3c 3c 3c 7c  3c 3c 3c 7c 7c 7c 3c 7c  |<<<|<<<|<<<|||<||
000011a0  7c 7c 22 02 20 00 33 33  03 00 00 00 00 00 00 00  |||". .33........|
000011b0  00 00 00 00 00 00 4b 00  00 00 00 00 00 00 00 00  |......K.........|
000011c0  00 00 00 00 00 00 00 00  00 00 00 00 00 0e 0e 03  |................|
000011d0  00 2d e2 00 02 0e 1c 00  00 00 00 00 00 00 00 00  |.-..............|
000011e0  00 00 00 00 00 00 00 00  00 23 00 00 00 00 00 00  |.........#......|
000011f0  00 00 00 00 00 00 00 30  48 58 70 8c a8 b8 d0 ec  |.......0HXp.....|
00001200  00 91 00 00 00 f5 00 91  00 00 00 f9 00 91 00 00  |................|
00001210  00 ff 00 91 00 00 00 02  00 90 00 00 00 00 00 91  |................|
00001220  00 00 00 fc 00 8f 00 00  00 f6 00 8f 00 00 00 f2  |................|
00001230  00 90 00 00 00 f8 00 90  00 00 00 fa 00 91 00 00  |................|
00001240  00 fe 00 90 00 00 00 00  00 90 00 00 00 fd 00 90  |................|
00001250  00 00 00 fb 00 8e 00 00  00 f3 00 8f 00 00 00 7f  |................|
00001260  00 82 00 00 00 7f 00 82  00 00 00 7f 00 82 00 00  |................|
00001270  00 7f 00 82 00 00 00 7f  00 82 00 00 00 7f 00 82  |................|
00001280  00 00 00 7f 00 82 00 00  00 7f 00 82 00 00 00 30  |...............0|
00001290  48 58 70 8c a8 b8 d0 30  48 58 70 8c a8 b8 d0 30  |HXp....0HXp....0|
000012a0  48 58 70 8c a8 b8 d0 23  23 23 23 23 23 23 23 23  |HXp....#########|
000012b0  23 23 23 23 23 23 23 23  23 23 23 23 23 23 23 23  |################|
000012c0  23 23 23 23 23 23 23 23  22 21 20 1f 1c 21 20 1f  |########"! ..! .|
000012d0  1c 21 20 1f 1c 23 22 21  20 1f 1c 21 20 1f 1c 21  |.! ..#"! ..! ..!|
000012e0  20 1f 1c 23 22 21 20 1f  1c 21 20 1f 1c 21 20 1f  | ..#"! ..! ..! .|
000012f0  1c 23 22 21 20 1f 1c 21  20 1f 1c 21 20 1f 1c 23  |.#"! ..! ..! ..#|
00001300  22 21 20 1f 1c 21 20 1f  1c 21 20 1f 1c 23 22 21  |"! ..! ..! ..#"!|
00001310  20 1f 1c 21 20 1f 1c 21  20 1f 1c 23 22 21 20 1f  | ..! ..! ..#"! .|
00001320  1c 21 20 1f 1c 21 20 1f  1c 23 22 21 20 1f 1c 21  |.! ..! ..#"! ..!|
00001330  20 1f 1c 21 20 1f 1c 23  22 21 20 1f 1c 21 20 1f  | ..! ..#"! ..! .|
00001340  1c 21 20 1f 1c 23 22 21  20 1f 1c 21 20 1f 1c 21  |.! ..#"! ..! ..!|
00001350  20 1f 1c 23 22 21 20 1f  1c 21 20 1f 1c 21 20 1f  | ..#"! ..! ..! .|
00001360  1c 23 22 21 20 1f 1c 21  20 1f 1c 21 20 1f 1c 23  |.#"! ..! ..! ..#|
00001370  22 21 20 1f 1c 21 20 1f  1c 21 20 1f 1c 23 22 21  |"! ..! ..! ..#"!|
00001380  20 1f 1c 21 20 1f 1c 21  20 1f 1c 23 22 21 20 1f  | ..! ..! ..#"! .|
00001390  1c 21 20 1f 1c 21 20 1f  1c 23 22 21 20 1f 1c 21  |.! ..! ..#"! ..!|
000013a0  20 1f 1c 21 20 1f 1c 10  16 18 40 46 48 30 36 38  | ..! .....@FH068|
000013b0  4c 5c 60 8c a0 b4 bd cd  4c 5c 60 8c 90 b4 bd cd  |L\`.....L\`.....|
000013c0  4e 56 5e 66 8e 96 ae bf  4c 50 5c 68 8c b4 ff ff  |NV^f....LP\h....|
000013d0  4c 5c 8c b4 ff ff ff ff  4e 5e 66 8e 9e ae ff ff  |L\......N^f.....|
000013e0  4c 50 54 5c 8c a0 b4 bd  4c 5c 68 8c 98 b4 bd cd  |LPT\....L\h.....|
000013f0  4e 56 5e 8e 96 ae bf c7  7c 7c 7c 7c 7c 7c 7c 3c  |NV^.....|||||||<|
00001400  7c 7c 7c 7c 7c 7c 7c 3c  3c 7c 3c 7c 7c 7c 7c 7c  ||||||||<<|<||||||
00001410  3c 7c 7c 3c 7c 3c 3c 3c  7c 7c 7c 3c 3c 3c 3c 3c  |<||<|<<<|||<<<<<|
00001420  7c 7c 7c 7c 7c 3c 3c 3c  7c 7c 7c 7c 7c 7c 7c 7c  ||||||<<<|||||||||
00001430  7c 7c 3c 7c 7c 7c 7c 3c  7c 3c 7c 7c 7c 7c 3c 7c  |||<||||<|<||||<||
00001440  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00100000

And yes, we used firmware that was installed on board (KIT).

**Comment by mantas-p** [comment]
Looks correct...
Please try upgrading device with image from (http://pkg.8devices.com/rambutan/v2.9/openwrt-8devices-v2.9-ar71xx-nand-rambutan-squashfs-nand-sysupgrade.tar) - use this command:

```sysupgrade -n /tmp/openwrt-8devices-v2.9-ar71xx-nand-rambutan-squashfs-nand-sysupgrade.tar```

If problem persists, report output of this command:
```ls -l /lib/firmware/soc_wmac.eeprom```

**Comment by alex-nozhkin** [comment]
Thank you very much. Wi-Fi now enabled.
