### ISSUE TITLE
Make KinKan target OpenWRT compatible

### ISSUE THREAD

**Issue by p4u** [8devices/openwrt-8devices#10]
Following #9

Update to kernel > 3.18 and make the proper changes to merge it with official OpenWRT source code.

Not being part of OpenWRT is a big barrier for developers and people willing to use the KinKan hardware.

**Comment by tapper82** [comment]
+1

**Comment by valinskas** [comment]
While i agree with sentiment, v3.18 is still better than what comes in original Realtek SDK (v3.10) even if it is just somewhat more newer kernel version only. Moving Kinkan/Komikan support openwrt upstream (v4.19.x, or v5.4.x kernel porting) is a major undertaking and at this moment 8devices have no resources to push forward unfromatunately. 

The usual pull requests are accepted disclaimer applies.
