### ISSUE TITLE
kinkan: kernel hangs during boot

### ISSUE THREAD

**Issue by niziak** [8devices/openwrt-8devices#11]
I'he just build latest version from https://github.com/8devices/openwrt-8devices/commit/08fd4b43aba5310783fe6a39d25da761c9eb2633

after sysupgrade kernel hangs during boot. Console log attached.
[bootlog.txt](https://github.com/8devices/openwrt-8devices/files/3485022/bootlog.txt)

**Comment by mantas-p** [comment]
Please try updating bootloader using istructions at: https://www.8devices.com/wiki/kinkan:realtek
Use latest bootloader binary from: http://pkg.8devices.com/kinkan/bootloader/rtl8197f_boot_tftp_v2.4.bin
