### ISSUE TITLE
 low

### ISSUE THREAD

**Issue by suyuan168** [8devices/openwrt-8devices#12]

**Comment by mantas-p** [comment]
Habanero definitely should support better speed on USB3. I don't have USB3 network adapter at hand, but tested with USB3 flash drives:

Drive 1 (8GB) - 796 Mbit/s
Drive 2(256GB) - 1185Mbit/s
For comparison on a PC, with same flash drives, I get 1024Mbit/s and 1366Mbit/s respectively.

I used dd to test read speed:

```
time dd if=/dev/sda of=/dev/null bs=16M count=64
```
This reads 1GiB of data and reports total time it took. Throughput(Mbit/s) = 1024MB * 8bits * time(s)


Can you confirm that your AX88179 dongle works well on a (preferably Linux) PC? Dongle itself may be somewhat flaky.
I suggest to test speed with flash drives (and confirm their max speed with PC).

**Comment by suyuan168** [comment]
I used ax88179 and tested the maximum speed of 950mbps on ubuntu.
I used your latest official firmware version. The test is not good. I have already sent the test results and logs to the technical support using the work order. I need to use the openwrt snapshot version. The kernel is 5.4.

**Comment by suyuan168** [comment]
> Habanero definitely should support better speed on USB3. I don't have USB3 network adapter at hand, but tested with USB3 flash drives:
> 
> Drive 1 (8GB) - 796 Mbit/s
> Drive 2(256GB) - 1185Mbit/s
> For comparison on a PC, with same flash drives, I get 1024Mbit/s and 1366Mbit/s respectively.
> 
> I used dd to test read speed:
> 
> ```
> time dd if=/dev/sda of=/dev/null bs=16M count=64
> ```
> 
> This reads 1GiB of data and reports total time it took. Throughput(Mbit/s) = 1024MB * 8bits * time(s)
> 
> Can you confirm that your AX88179 dongle works well on a (preferably Linux) PC? Dongle itself may be somewhat flaky.
> I suggest to test speed with flash drives (and confirm their max speed with PC).

I used ax88179 and tested the maximum speed of 950mbps on ubuntu.
I used your latest official firmware version. The test is not good. I have already sent the test results and logs to the technical support using the work order. I need to use the openwrt snapshot version. The kernel is 5.4.
