### ISSUE TITLE
How to Flash Mango Dev Kit Firmware if bricked

### ISSUE THREAD

**Issue by brent7984** [8devices/openwrt-8devices#15]
Hi, I am evaluating the Mango Dev Kits. How do I go about flashing the firmware onto the boards? I am afraid of bricking the boards. However, if I do manage to brick it, how do I go about re-flashing the firmware? Note, I have successfully built and compiled the firmware image "openwrt-8devices-4.0-ipq60xx"

With thanks
Brenton

**Comment by valinskas** [comment]
Please see https://www.8devices.com/wiki/mango sections below: flashing, upgrading and recovering.

**Comment by brent7984** [comment]
Thank you, I somehow did not see that information before. But I've noticed that those recovery methods are not for bricked boards. How do I re-flash the boards if I cannot access the board via IP (i.e. If I flash corrupted firmware onto it)

**Comment by valinskas** [comment]
recovery via u-boot: https://www.8devices.com/wiki/mango:recover

Openwrt sysupgrade does not touch uboot and related things. So you should be able to recover device if openwrt does not boot. If you by accident somehow overwrite or corrupt bootloader then board is really bricked. There is almost nothting short of soldering flash off, program bootloader and re-solder back.

**Comment by brent7984** [comment]
Thank you
