### ISSUE TITLE
802.11s mesh support for Mango Dev Kits

### ISSUE THREAD

**Issue by brent7984** [8devices/openwrt-8devices#16]
Hi, is 802.11s mesh supported on the Mango Dev kits? I contacted Openwrt directly, they said that they do not support the kernel 4.4.60 anymore (Mango Openwrt Kernel). If not supported, are there any alternatives for a mesh network which are supported?

Regards
Brenton

**Comment by alfiedouglas-tewke** [comment]
@brent7984 did you find an answer to this?

**Comment by brent7984** [comment]
No, I have not

**Comment by valinskas** [comment]
Hi,

Linux kernel v4.4.60 comes from Qualcomm. Mango DVK is not based on openwrt upstream either. Instead it is based on Qsdk which is qualcomm fork of openwrt version. Please clone the repository, run make menuconfig and check there if 802.11s is supported or not.
