### ISSUE TITLE
WiFi in mode client

### ISSUE THREAD

**Issue by alex-nozhkin** [8devices/openwrt-8devices#2]
Hi!

We have an issue which can be marked as "well known", but may be you can give us a recommendation.

We have the test site which include:
1) PC with wireless interface. IP address of this interface is 192.168.2.44.
2) Rambutan-DVK (Linux Rambutan 4.1.23 #1 Tue Jun 28 16:32:15 UTC 2016 mips GNU/Linux got from http://pkg.8devices.com/rambutan/v2.9/openwrt-8devices-v2.9-ar71xx-nand-rambutan-squashfs-nand-sysupgrade.tar) in the bridge mode (gigabit ethernet and wireless interface are combined). IP address of this interface is 192.168.2.60.
3) "Some device" connected to the gigabit ethenet interface of the Rambutan-DVK. IP address of this interface is 192.168.2.4.

When we try to ping the Rambutan-bridge from the PC - we have success in any case. But when we try to ping "Some device" from the PC, we can reach it only if the wireless interface of Rambutan-bridge in the AP mode. If we switch this interface in the client mode - ping does not pass. Also we conclude that ARP requests (which usually precede the ICMP requests) does not pass too (we use the Wireshark on the PC side - no any ARP replies here). We know that this problem is caused by the specific requirements of the Wi-Fi standarts. This standarts (as mentioned in some internet forums) does not allow multiple source MACs on the wireless interface in client mode (multiple source MACs allowed only in AP mode). But guys from this forums also mentioned that some wireless adaptors have the drivers which fix this problem. May be you know - do we can to find appropriate driver for the Rambutan module? It is neccesary for the full bridge functionality (and we know that some wireless bridges can do it).

Thanks a lot!

**Comment by valinskas** [comment]
I am just closing the issue, 4years later.
