### ISSUE TITLE
Cannot build with ubuntu 16.04.7 LTS

### ISSUE THREAD

**Issue by lslrt** [8devices/openwrt-8devices#20]
Hi,

I'm trying to build a firmware for the mango-dvk board.
I follow the instructions: https://www.8devices.com/wiki/mango:build
I got the following error:
```
scripts/config/conf: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by scripts/config/conf)
/src_openwrt/include/toplevel.mk:103: recipe for target 'defconfig' failed
make: *** [defconfig] Error 1
```
Here is my setup:
```
# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```

I've tried to build using ubuntu 18.04 that have the correct glibc version but cannot build uboot.
Any advice?

**Comment by valinskas** [comment]
`scripts/config/conf` is linked against glibc 2.27 (ubuntu/bionic?) version. if try running on xenial (which is glibc 2.23!), it would not run will complain like above. You have to rebuild 'scripts/config/conf' somehow and try it again (try removing it) and running make.

**Comment by lslrt** [comment]
Good catch, need to sleep.
Since I'm building from a container, I've certainly run make on the host before trying the container.
Anyway, thanks.
