### ISSUE TITLE
Add kinkan target to official OpenWRT

### ISSUE THREAD

**Issue by p4u** [8devices/openwrt-8devices#9]
Pleasae, send the proper pull request to official openwrt source repository so Kinkan can be build using the standard build root.

https://github.com/8devices/openwrt-8devices/blob/openwrt-18.06-rtkmipsel-3.18/target/linux/rtkmipsel/Makefile

**Comment by mantas-p** [comment]
It will not get accepted as it is now. OpenWRT is planning to deprecate all target that still use 3.18 kernel.
